#!/usr/bin/with-contenv sh

if [ ! ${DATALOOP_SERVER} ] ; then
  DATALOOP_SERVER="https://agent.dataloop.io"
fi

echo "Starting dataloop-agents"
exec /usr/bin/python \
     /opt/dataloop/embedded/bin/agents.py -a $DATALOOP_AGENT_KEY -u $DATALOOP_SERVER
