#!/bin/bash

curl -s -XPOST -H "Content-type: application/json" \
     -H "Authorization: Bearer $DATALOOP_AGENT_KEY" \
     https://stag-agent.dataloop.io/agents/$(curl -s http://localhost:8000)/deregister
# exec /usr/bin/python /opt/dataloop/agent/agent.py --config /etc/dataloop/agent.yaml --deregister >/dev/stdout 2>&1
echo "tried dereged" >/dev/stdout 2>&1

# # only tell s6 to bring down the entire container, if it isn't already doing so
# # http://skarnet.org/software/s6/s6-supervise.html
# if { s6-test ${1} -ne 0 }
# if { s6-test ${1} -ne 256 }
# 
# s6-svscanctl -t /var/run/s6/services
