---
before_script:
  # verify docker access
  - docker info
  # - export BUILD_TAG=$(git describe --tags)
  

stages:
  - build_branch
  - build_release

variables:
  GIT_SUBMODULE_STRATEGY: recursive

branch_agent:
  stage: build_branch
  only:
    - branches
  except:
    - master
  tags:
    - docker-build
  script:
    - export
    - docker login -u ${docker_gitlab_login} -p ${docker_gitlab_pass} docker.dataloop.io
    - docker build -t docker.dataloop.io/agent:${CI_COMMIT_REF_SLUG} ./agent/
    - docker push docker.dataloop.io/agent:${CI_COMMIT_REF_SLUG}


master_agent:
  stage: build_release
  only:
    - tags
  tags:
    - docker-build
  script:
    - export
    - docker login -u ${docker_hub_login} -p ${docker_hub_pass} hub.docker.com
    - docker build -t outlyer/agent:${CI_COMMIT_TAG} ./agent/
    - docker push outlyer/agent:${CI_COMMIT_TAG}
