---
before_script:
  # verify docker access
  - docker info
  

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_TAG: 'git describe --tags'
script:
  - 'eval $BUILD_TAG'

agent:
  stage: build
  tags:
    - docker-build
  script:
    - cd agent/ 
    - docker build -t outlyer/agent:$BUILD_TAG-1
