---
before_script:
  # verify docker access
  - docker info
  

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

agent:
  stage: build
  variables:
    BUILD_TAG: git describe --tags
  tags:
    - docker-build
  script:
    - 'export $(BUILD_TAG)'
    - cd agent/ 
    - "docker build -t outlyer/agent:$BUILD_TAG-1"
