---
before_script:
  # verify docker access
  - docker info
  # - export BUILD_TAG=$(git describe --tags)
  

stages:
  - build_branch
  - build_release

variables:
  GIT_SUBMODULE_STRATEGY: recursive

branch_agent:
  stage: build_branch
  only:
    - branches
  except:
    - master
  tags:
    - docker-build
  script:
    - export
    - docker build -t outlyer/agent:${CI_COMMIT_REF_SLUG} ./agent/


master_agent:
  stage: build_release
  only:
    - tags
  tags:
    - docker-build
  script:
    - export
    - docker build -t outlyer/agent:${CI_COMMIT_TAG} ./agent/
