---
before_script:
  # verify docker access
  - docker info

stages:
  - build

agent:
  stage: build
  tags:
    - docker-build
  script:
    - cd agent/ 
    - docker build -t outlyer/agent:latest .
