---
before_script:
  # verify docker access
  - docker info
  - export BUILD_TAG=$(git describe --tags)
  

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

agent:
  stage: build
  tags:
    - docker-build
  script:
    - cd agent/ 
    - export
    - docker build -t outlyer/agent:${BUILD_TAG}-1
