#!/usr/bin/with-contenv sh

if [ ! -f /etc/dataloop/agent.finger ]; then
    echo "No fingerprint to serve"
    sleep 10
fi

FINGERPRINT=$(grep fingerprint /etc/dataloop/agent.finger | cut -d\  -f3)
echo ${FINGERPRINT} > /var/run/s6/services/dataloop-fingerprint/index.html

exec python2 -m SimpleHTTPServer 8000;
