version: '3.1'

services:
    agent-worker:
        image: outlyer/agent:latest
        environment:
          - DATALOOP_AGENT_KEY=<your dataloop agent key>
          - DATALOOP_NAME={{.Node.ID}}
          - DATALOOP_TAGS=docker,swarm,swarm-worker
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - /proc:/rootfs/proc:ro
          - /sys/fs/cgroup:/rootfs/sys/fs/cgroup:ro
        deploy:
            mode: global
            placement:
                constraints: 
                  - node.role != manager
            
    agent-manager:
        image: outlyer/agent:latest
        environment:
          - DATALOOP_AGENT_KEY=<your dataloop agent key>
          - DATALOOP_NAME={{.Node.ID}}
          - DATALOOP_TAGS=docker,swarm,swarm-manager
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - /proc:/rootfs/proc:ro
          - /sys/fs/cgroup:/rootfs/sys/fs/cgroup:ro
        deploy:
            mode: global
            placement:
                constraints: 
                  - node.role == manager
