#!/usr/bin/with-contenv sh

if [ ! ${GRAPHITE_SERVER} ] ; then
  GRAPHITE_SERVER="graphite.dataloop.io"
fi

if [ ! ${GRAPHITE_PORT} ] ; then
  GRAPHITE_PORT=2003
fi

echo "Starting container metrics collection"
exec /usr/bin/python \
     /opt/dataloop/embedded/bin/metrics.py -s $GRAPHITE_SERVER -p $GRAPHITE_PORT
